# docker compose used for local development
version: '3.7'

services:
    backend:
        build:
            context: ./backend
        ports:
            - "8000:8000"
        volumes: 
            - static_data:/vol/web
            
        env_file:
            - ./backend/.env

    client:
        build:
            context: ./client
        volumes: 
            - react_build:/react/build

    nginx:
        build:
            context: ./nginx
        ports:
            - "80:8080"
        volumes:
            - react_build:/var/www/react
            - static_data:/vol/static
        depends_on: 
            - backend
            - client
volumes:
    react_build:
    static_data:

