# docker compose used for local development
version: '3.7'

services:
    backend:
        build:
            context: backend
        ports:
            - "8000:8000"
        volumes: 
            - ./backend:/django
        command: sh -c "python manage.py runserver 0.0.0.0:8000"
        environment: 
            - DEBUG=1