const products = [
  {
    _id: '1',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas1.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Purple/Yellow/Orange/Grey Stripes, 1992',
    material: 'MArchival pigment print',
    width: 580,
    height: 15,
    price: 89.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
    aboutWork:
      'نقاشی، نگارگری یا رسم، فرایندی است که طی آن رنگ، رنگدانه یا رنگ نقاشی بر روی یک سطح مسطح مانند کاغذ یا بوم ایجاد نقش می‌کند و اثری خلق می‌شود. فردی که این فرایند توسط او انجام می‌گیرد نقاش نام دارد، به‌خصوص زمانی که نقاشی حرفهٔ شخص باشد.نقاشی یکی از رشته‌های اصلی هنرهای تجسمی است و قدمت آن شش برابر زبان نوشتاری می‌باشد.[۱] برخی از پژوهشگران معتقدند اولین نقاشی‌های یافت‌شده در غارها حاکی از آن است که انسان‌های اولیه با کشیدن نقش حیوانات و شکارشان به نوعی خود را آمادهٔ نبرد با آن‌ها می‌کرده‌اند.قدیمی‌ترین نقاشی‌ها در جهان که متعلق به حدود ۳۲۰۰۰ هزار سال پیش می‌باشد، در گروته شاوه فرانسه قرار دارد. این نقاشی‌ها که با استفاده از افرای قرمز و رنگ‌دانه سیاه، حکاکی و رنگ شده‌اند، تصاویری از اسب‌ها، کرگدن‌ها، شیرها، بوفالوها و ماموت‌ها را نشان می‌دهند. این‌ها نمونه‌هایی از نقاشی در غار هستند که در اغلب نقاط جهان وجود دارند.بسیاری از آثار شناخته شده و مشهور هنری امروزی، مانند مونالیزا، شب پرستاره، دختری با گوشواره مروارید و تولد ونوس نقاشی‌های برجسته‌ای هستند که در سراسر جهان از آن‌ها الگو برداری شده‌است. هرچند اختلاف نظرهای ',
  },
  {
    _id: '2',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas2.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Archival pigment printr',
    width: 75,
    height: 14,
    price: 89.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '3',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas3.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'MNovember Conversation , 2014',
    material: 'Monotype Ink on Paper',
    width: 180,
    height: 72,
    price: 89.702,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '4',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas4.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'November Conversation , 2014',
    material: 'Oil on board',
    width: 180,
    height: 15,
    price: 50.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '5',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas5.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 86,
    height: 75,
    price: 89.2,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '6',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas6.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 333,
    height: 15,
    price: 223.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '7',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas7.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 680,
    height: 15,
    price: 878.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '8',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas8.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 18,
    height: 15,
    price: 89.9,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '9',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas9.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 180,
    height: 5,
    price: 89.9,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '10',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas10.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 222,
    height: 75,
    price: 75.41,
    countInStock: 170,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '11',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas11.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 160,
    height: 175,
    price: 89.997,
    countInStock: 12,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '12',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas12.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 83,
    height: 742,
    price: 222.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '13',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas13.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 180,
    height: 15,
    price: 89.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '14',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas14.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 472,
    height: 72,
    price: 839.99,
    countInStock: 1580,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '15',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas15.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 752,
    height: 17,
    price: 39.75,
    countInStock: 11,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '16',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas16.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 190,
    height: 25,
    price: 89.39,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
  {
    _id: '17',
    artist: 'Airpods Wireless Bluetooth Headphones',
    biography:
      'The Connor Brothers are known for their paintings and prints featuring vintage pin-up beauties and Old Hollywood starlets in seductive poses, paired with captions that exude a dry sense of humor. The Connor Brothers—a pseudonym for the British artists Mike Snelle and James Golding—initially retained anonymity under their fictional guise. They posed as fictional twin brothers Franklyn and Brendan Connor, who had escaped from a California cult (called “The Family”) by running away to Brooklyn at age 16 to become artists. Today, Snelling and Golding have shed their guise, and align their work with social causes such as the European refugee crisis. ',
    image: '/images/canvas17.png',
    caption:
      'Bubblegum Ranger, ca. 200-2019 Original hand-pulled acrylic polymer serigraph/silkscreen on archival paper with deckled edges.',
    colors: 'Monotype Ink on Paper',
    material: 'Monotype Ink on Paper',
    width: 80,
    height: 5,
    price: 8.99,
    countInStock: 10,
    shipmentOrigin: 'Ships from Chicago, IL, US',
    shipmentDescription: 'Shipping: $250 domestic, $300 rest of world',
    gallery: {
      name: 'Reem Gallery',
      location: 'Chicago',
    },
    medium: 'painting',
    signuture: 'Hand-sighned by artist',
    certificate: 'included',
    frame: 'included',
  },
];

export default products;
