# Generated by Django 3.1.7 on 2021-03-22 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('artworks', '0002_auto_20210321_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('paymentMethod', models.CharField(blank=True, max_length=200, null=True)),
                ('isPaid', models.BooleanField(default=False)),
                ('paidAt', models.DateTimeField(blank=True, null=True)),
                ('shippigDesc', models.CharField(blank=True, max_length=1200, null=True)),
                ('shippigPrice', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('feePrice', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('totalPrice', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('deliveredAt', models.DateTimeField(blank=True, null=True)),
                ('createAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='biography',
            new_name='medium',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='artist',
        ),
        migrations.AddField(
            model_name='artwork',
            name='classifications',
            field=models.CharField(choices=[('1', 'Unique'), ('2', 'Limited edition'), ('3', 'Open edition'), ('4', 'Unknown edition')], default='cm', max_length=20),
        ),
        migrations.AddField(
            model_name='artwork',
            name='depth',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='editionNum',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='editionSize',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='artwork',
            name='isAnEdition',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='isAuthenticated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='isSigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='unit',
            field=models.CharField(choices=[('US', 'in'), ('UK', 'cm')], default='', max_length=2),
        ),
        migrations.AddField(
            model_name='artwork',
            name='year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='frame',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True)),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
                ('artwork', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.artwork')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artworks.order')),
            ],
        ),
    ]
