# Generated by Django 3.1.7 on 2021-03-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0017_auto_20210323_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='provenance',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
