# Generated by Django 3.1.7 on 2021-03-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0020_remove_order_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(choices=[('1', 'خرید'), ('2', 'تماس با گالری')], default='خرید', max_length=20),
        ),
    ]
