# Generated by Django 3.1.7 on 2021-03-25 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0021_order_paymentmethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='classifications',
            field=models.CharField(choices=[('1', 'Unique'), ('2', 'Limited edition'), ('3', 'Open edition'), ('4', 'Unknown edition')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='unit',
            field=models.CharField(choices=[('0', 'in'), ('1', 'cm')], default='', max_length=2),
        ),
    ]
