# Generated by Django 3.1.7 on 2021-03-25 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0022_auto_20210325_1708'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='caption',
            new_name='condition',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='artwork',
            old_name='color',
            new_name='subtitle',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='material',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='stockCount',
        ),
        migrations.AddField(
            model_name='artwork',
            name='isPrice',
            field=models.BooleanField(default=False),
        ),
    ]
