# Generated by Django 3.1.7 on 2021-03-25 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0023_auto_20210325_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='artLocation',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
