# Generated by Django 3.1.7 on 2021-04-09 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0024_artwork_artlocation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='feePrice',
            new_name='shippingPrice',
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentMethod',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
