# Generated by Django 3.1.7 on 2021-04-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0025_auto_20210409_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
