# Generated by Django 3.1.7 on 2021-04-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0026_artwork_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='shippigDesc',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
