export const ARTWORK_LIST_REQUEST = 'ARTWORK_LIST_REQUEST';
export const ARTWORK_LIST_SUCCESS = 'ARTWORK_LIST_SUCCESS';
export const ARTWORK_LIST_FAIL = 'ARTWORK_LIST_FAIL';

export const ARTWORK_DETAILS_REQUEST = 'ARTWORK_DETAILS_REQUEST';
export const ARTWORK_DETAILS_SUCCESS = 'ARTWORK_DETAILS_SUCCESS';
export const ARTWORK_DETAILS_FAIL = 'ARTWORK_DETAILS_FAIL';
